################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
/home/lu/Projects/STM32CubeExpansion_Cloud_AZURE_V1.2.1/Projects/B-L475E-IOT01A/Applications/Cloud/Azure/Src/flash_l4.c \
/home/lu/Projects/STM32CubeExpansion_Cloud_AZURE_V1.2.1/Projects/B-L475E-IOT01A/Applications/Cloud/Azure/Src/main.c \
/home/lu/Projects/STM32CubeExpansion_Cloud_AZURE_V1.2.1/Projects/B-L475E-IOT01A/Applications/Cloud/Azure/Src/mbedtls_entropy.c \
/home/lu/Projects/STM32CubeExpansion_Cloud_AZURE_V1.2.1/Projects/B-L475E-IOT01A/Applications/Cloud/Azure/Src/net_conf.c \
/home/lu/Projects/STM32CubeExpansion_Cloud_AZURE_V1.2.1/Projects/B-L475E-IOT01A/Applications/Cloud/Azure/Src/stm32l4xx_hal_msp.c \
/home/lu/Projects/STM32CubeExpansion_Cloud_AZURE_V1.2.1/Projects/B-L475E-IOT01A/Applications/Cloud/Azure/Src/stm32l4xx_it.c \
/home/lu/Projects/STM32CubeExpansion_Cloud_AZURE_V1.2.1/Projects/B-L475E-IOT01A/Applications/Cloud/Azure/Src/vl53l0x_platform.c \
/home/lu/Projects/STM32CubeExpansion_Cloud_AZURE_V1.2.1/Projects/B-L475E-IOT01A/Applications/Cloud/Azure/Src/vl53l0x_proximity.c 

OBJS += \
./Application/User/flash_l4.o \
./Application/User/main.o \
./Application/User/mbedtls_entropy.o \
./Application/User/net_conf.o \
./Application/User/stm32l4xx_hal_msp.o \
./Application/User/stm32l4xx_it.o \
./Application/User/vl53l0x_platform.o \
./Application/User/vl53l0x_proximity.o 

C_DEPS += \
./Application/User/flash_l4.d \
./Application/User/main.d \
./Application/User/mbedtls_entropy.d \
./Application/User/net_conf.d \
./Application/User/stm32l4xx_hal_msp.d \
./Application/User/stm32l4xx_it.d \
./Application/User/vl53l0x_platform.d \
./Application/User/vl53l0x_proximity.d 


# Each subdirectory must supply rules for building sources it contributes
Application/User/flash_l4.o: /home/lu/Projects/STM32CubeExpansion_Cloud_AZURE_V1.2.1/Projects/B-L475E-IOT01A/Applications/Cloud/Azure/Src/flash_l4.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32L475xx -DUSE_HAL_DRIVER -DSENSOR '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -DENABLE_IOT_INFO -DENABLE_IOT_ERROR -DENABLE_IOT_WARNING -DDONT_USE_UPLOADTOBLOB -DAZURE -DUSE_MBED_TLS -DHSM_TYPE_X509 -DHSM_TYPE_SAS_TOKEN -DUSE_PROV_MODULE '-DEINVAL=22' '-DENOMEM=12' '-DSTRINGS_C_SPRINTF_BUFFER_SIZE=512' -DUSE_WIFI -c -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSPv2/B-L475E-IOT01 -I../../../Inc -I../../../../../../../../Middlewares/ST/STM32_Connect_Library/Includes -I../../../../../../../../Middlewares/ST/STM32_Secure_Engine/Core -I../../../../../BootLoader_OSC/2_Images_SECoreBin/Inc -I../../../../../BootLoader_OSC/2_Images_SBSFU/SBSFU/App -I../../../../../BootLoader_OSC/Linker_Common/SW4STM32 -I../../../../../../../Misc_Utils/Inc -I../../../../../../../../Utilities/Time -I../../../../../../../../Utilities/CLD_utils/http_lib -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/umqtt/inc -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/iothub_client/inc -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/iothub_client/samples/STM32Cube_sample -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/provisioning_client/adapters -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/provisioning_client/inc -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/provisioning_client/deps/RIoT/Emulator/RIoT -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/provisioning_client/deps/RIoT/Emulator/DICE -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/provisioning_client/deps/RIoT/Emulator/RIoT/RIoTCrypt/include -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/c-utility/inc -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/serializer/inc -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/deps/parson -I../../../../../../../../Middlewares/Third_Party/mbedTLS/include -I../../../../../../../../Drivers/BSPv2/Components/es_wifi -I../../../../../../../../Drivers/BSPv2/Components/vl53l0x -I../../../../../BootLoader_OSC/Linker_Common -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Application/User/flash_l4.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/main.o: /home/lu/Projects/STM32CubeExpansion_Cloud_AZURE_V1.2.1/Projects/B-L475E-IOT01A/Applications/Cloud/Azure/Src/main.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32L475xx -DUSE_HAL_DRIVER -DSENSOR '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -DENABLE_IOT_INFO -DENABLE_IOT_ERROR -DENABLE_IOT_WARNING -DDONT_USE_UPLOADTOBLOB -DAZURE -DUSE_MBED_TLS -DHSM_TYPE_X509 -DHSM_TYPE_SAS_TOKEN -DUSE_PROV_MODULE '-DEINVAL=22' '-DENOMEM=12' '-DSTRINGS_C_SPRINTF_BUFFER_SIZE=512' -DUSE_WIFI -c -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSPv2/B-L475E-IOT01 -I../../../Inc -I../../../../../../../../Middlewares/ST/STM32_Connect_Library/Includes -I../../../../../../../../Middlewares/ST/STM32_Secure_Engine/Core -I../../../../../BootLoader_OSC/2_Images_SECoreBin/Inc -I../../../../../BootLoader_OSC/2_Images_SBSFU/SBSFU/App -I../../../../../BootLoader_OSC/Linker_Common/SW4STM32 -I../../../../../../../Misc_Utils/Inc -I../../../../../../../../Utilities/Time -I../../../../../../../../Utilities/CLD_utils/http_lib -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/umqtt/inc -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/iothub_client/inc -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/iothub_client/samples/STM32Cube_sample -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/provisioning_client/adapters -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/provisioning_client/inc -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/provisioning_client/deps/RIoT/Emulator/RIoT -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/provisioning_client/deps/RIoT/Emulator/DICE -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/provisioning_client/deps/RIoT/Emulator/RIoT/RIoTCrypt/include -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/c-utility/inc -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/serializer/inc -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/deps/parson -I../../../../../../../../Middlewares/Third_Party/mbedTLS/include -I../../../../../../../../Drivers/BSPv2/Components/es_wifi -I../../../../../../../../Drivers/BSPv2/Components/vl53l0x -I../../../../../BootLoader_OSC/Linker_Common -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Application/User/main.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/mbedtls_entropy.o: /home/lu/Projects/STM32CubeExpansion_Cloud_AZURE_V1.2.1/Projects/B-L475E-IOT01A/Applications/Cloud/Azure/Src/mbedtls_entropy.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32L475xx -DUSE_HAL_DRIVER -DSENSOR '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -DENABLE_IOT_INFO -DENABLE_IOT_ERROR -DENABLE_IOT_WARNING -DDONT_USE_UPLOADTOBLOB -DAZURE -DUSE_MBED_TLS -DHSM_TYPE_X509 -DHSM_TYPE_SAS_TOKEN -DUSE_PROV_MODULE '-DEINVAL=22' '-DENOMEM=12' '-DSTRINGS_C_SPRINTF_BUFFER_SIZE=512' -DUSE_WIFI -c -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSPv2/B-L475E-IOT01 -I../../../Inc -I../../../../../../../../Middlewares/ST/STM32_Connect_Library/Includes -I../../../../../../../../Middlewares/ST/STM32_Secure_Engine/Core -I../../../../../BootLoader_OSC/2_Images_SECoreBin/Inc -I../../../../../BootLoader_OSC/2_Images_SBSFU/SBSFU/App -I../../../../../BootLoader_OSC/Linker_Common/SW4STM32 -I../../../../../../../Misc_Utils/Inc -I../../../../../../../../Utilities/Time -I../../../../../../../../Utilities/CLD_utils/http_lib -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/umqtt/inc -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/iothub_client/inc -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/iothub_client/samples/STM32Cube_sample -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/provisioning_client/adapters -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/provisioning_client/inc -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/provisioning_client/deps/RIoT/Emulator/RIoT -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/provisioning_client/deps/RIoT/Emulator/DICE -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/provisioning_client/deps/RIoT/Emulator/RIoT/RIoTCrypt/include -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/c-utility/inc -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/serializer/inc -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/deps/parson -I../../../../../../../../Middlewares/Third_Party/mbedTLS/include -I../../../../../../../../Drivers/BSPv2/Components/es_wifi -I../../../../../../../../Drivers/BSPv2/Components/vl53l0x -I../../../../../BootLoader_OSC/Linker_Common -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Application/User/mbedtls_entropy.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/net_conf.o: /home/lu/Projects/STM32CubeExpansion_Cloud_AZURE_V1.2.1/Projects/B-L475E-IOT01A/Applications/Cloud/Azure/Src/net_conf.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32L475xx -DUSE_HAL_DRIVER -DSENSOR '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -DENABLE_IOT_INFO -DENABLE_IOT_ERROR -DENABLE_IOT_WARNING -DDONT_USE_UPLOADTOBLOB -DAZURE -DUSE_MBED_TLS -DHSM_TYPE_X509 -DHSM_TYPE_SAS_TOKEN -DUSE_PROV_MODULE '-DEINVAL=22' '-DENOMEM=12' '-DSTRINGS_C_SPRINTF_BUFFER_SIZE=512' -DUSE_WIFI -c -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSPv2/B-L475E-IOT01 -I../../../Inc -I../../../../../../../../Middlewares/ST/STM32_Connect_Library/Includes -I../../../../../../../../Middlewares/ST/STM32_Secure_Engine/Core -I../../../../../BootLoader_OSC/2_Images_SECoreBin/Inc -I../../../../../BootLoader_OSC/2_Images_SBSFU/SBSFU/App -I../../../../../BootLoader_OSC/Linker_Common/SW4STM32 -I../../../../../../../Misc_Utils/Inc -I../../../../../../../../Utilities/Time -I../../../../../../../../Utilities/CLD_utils/http_lib -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/umqtt/inc -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/iothub_client/inc -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/iothub_client/samples/STM32Cube_sample -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/provisioning_client/adapters -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/provisioning_client/inc -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/provisioning_client/deps/RIoT/Emulator/RIoT -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/provisioning_client/deps/RIoT/Emulator/DICE -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/provisioning_client/deps/RIoT/Emulator/RIoT/RIoTCrypt/include -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/c-utility/inc -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/serializer/inc -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/deps/parson -I../../../../../../../../Middlewares/Third_Party/mbedTLS/include -I../../../../../../../../Drivers/BSPv2/Components/es_wifi -I../../../../../../../../Drivers/BSPv2/Components/vl53l0x -I../../../../../BootLoader_OSC/Linker_Common -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Application/User/net_conf.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/stm32l4xx_hal_msp.o: /home/lu/Projects/STM32CubeExpansion_Cloud_AZURE_V1.2.1/Projects/B-L475E-IOT01A/Applications/Cloud/Azure/Src/stm32l4xx_hal_msp.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32L475xx -DUSE_HAL_DRIVER -DSENSOR '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -DENABLE_IOT_INFO -DENABLE_IOT_ERROR -DENABLE_IOT_WARNING -DDONT_USE_UPLOADTOBLOB -DAZURE -DUSE_MBED_TLS -DHSM_TYPE_X509 -DHSM_TYPE_SAS_TOKEN -DUSE_PROV_MODULE '-DEINVAL=22' '-DENOMEM=12' '-DSTRINGS_C_SPRINTF_BUFFER_SIZE=512' -DUSE_WIFI -c -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSPv2/B-L475E-IOT01 -I../../../Inc -I../../../../../../../../Middlewares/ST/STM32_Connect_Library/Includes -I../../../../../../../../Middlewares/ST/STM32_Secure_Engine/Core -I../../../../../BootLoader_OSC/2_Images_SECoreBin/Inc -I../../../../../BootLoader_OSC/2_Images_SBSFU/SBSFU/App -I../../../../../BootLoader_OSC/Linker_Common/SW4STM32 -I../../../../../../../Misc_Utils/Inc -I../../../../../../../../Utilities/Time -I../../../../../../../../Utilities/CLD_utils/http_lib -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/umqtt/inc -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/iothub_client/inc -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/iothub_client/samples/STM32Cube_sample -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/provisioning_client/adapters -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/provisioning_client/inc -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/provisioning_client/deps/RIoT/Emulator/RIoT -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/provisioning_client/deps/RIoT/Emulator/DICE -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/provisioning_client/deps/RIoT/Emulator/RIoT/RIoTCrypt/include -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/c-utility/inc -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/serializer/inc -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/deps/parson -I../../../../../../../../Middlewares/Third_Party/mbedTLS/include -I../../../../../../../../Drivers/BSPv2/Components/es_wifi -I../../../../../../../../Drivers/BSPv2/Components/vl53l0x -I../../../../../BootLoader_OSC/Linker_Common -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Application/User/stm32l4xx_hal_msp.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/stm32l4xx_it.o: /home/lu/Projects/STM32CubeExpansion_Cloud_AZURE_V1.2.1/Projects/B-L475E-IOT01A/Applications/Cloud/Azure/Src/stm32l4xx_it.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32L475xx -DUSE_HAL_DRIVER -DSENSOR '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -DENABLE_IOT_INFO -DENABLE_IOT_ERROR -DENABLE_IOT_WARNING -DDONT_USE_UPLOADTOBLOB -DAZURE -DUSE_MBED_TLS -DHSM_TYPE_X509 -DHSM_TYPE_SAS_TOKEN -DUSE_PROV_MODULE '-DEINVAL=22' '-DENOMEM=12' '-DSTRINGS_C_SPRINTF_BUFFER_SIZE=512' -DUSE_WIFI -c -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSPv2/B-L475E-IOT01 -I../../../Inc -I../../../../../../../../Middlewares/ST/STM32_Connect_Library/Includes -I../../../../../../../../Middlewares/ST/STM32_Secure_Engine/Core -I../../../../../BootLoader_OSC/2_Images_SECoreBin/Inc -I../../../../../BootLoader_OSC/2_Images_SBSFU/SBSFU/App -I../../../../../BootLoader_OSC/Linker_Common/SW4STM32 -I../../../../../../../Misc_Utils/Inc -I../../../../../../../../Utilities/Time -I../../../../../../../../Utilities/CLD_utils/http_lib -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/umqtt/inc -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/iothub_client/inc -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/iothub_client/samples/STM32Cube_sample -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/provisioning_client/adapters -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/provisioning_client/inc -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/provisioning_client/deps/RIoT/Emulator/RIoT -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/provisioning_client/deps/RIoT/Emulator/DICE -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/provisioning_client/deps/RIoT/Emulator/RIoT/RIoTCrypt/include -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/c-utility/inc -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/serializer/inc -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/deps/parson -I../../../../../../../../Middlewares/Third_Party/mbedTLS/include -I../../../../../../../../Drivers/BSPv2/Components/es_wifi -I../../../../../../../../Drivers/BSPv2/Components/vl53l0x -I../../../../../BootLoader_OSC/Linker_Common -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Application/User/stm32l4xx_it.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/vl53l0x_platform.o: /home/lu/Projects/STM32CubeExpansion_Cloud_AZURE_V1.2.1/Projects/B-L475E-IOT01A/Applications/Cloud/Azure/Src/vl53l0x_platform.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32L475xx -DUSE_HAL_DRIVER -DSENSOR '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -DENABLE_IOT_INFO -DENABLE_IOT_ERROR -DENABLE_IOT_WARNING -DDONT_USE_UPLOADTOBLOB -DAZURE -DUSE_MBED_TLS -DHSM_TYPE_X509 -DHSM_TYPE_SAS_TOKEN -DUSE_PROV_MODULE '-DEINVAL=22' '-DENOMEM=12' '-DSTRINGS_C_SPRINTF_BUFFER_SIZE=512' -DUSE_WIFI -c -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSPv2/B-L475E-IOT01 -I../../../Inc -I../../../../../../../../Middlewares/ST/STM32_Connect_Library/Includes -I../../../../../../../../Middlewares/ST/STM32_Secure_Engine/Core -I../../../../../BootLoader_OSC/2_Images_SECoreBin/Inc -I../../../../../BootLoader_OSC/2_Images_SBSFU/SBSFU/App -I../../../../../BootLoader_OSC/Linker_Common/SW4STM32 -I../../../../../../../Misc_Utils/Inc -I../../../../../../../../Utilities/Time -I../../../../../../../../Utilities/CLD_utils/http_lib -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/umqtt/inc -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/iothub_client/inc -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/iothub_client/samples/STM32Cube_sample -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/provisioning_client/adapters -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/provisioning_client/inc -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/provisioning_client/deps/RIoT/Emulator/RIoT -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/provisioning_client/deps/RIoT/Emulator/DICE -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/provisioning_client/deps/RIoT/Emulator/RIoT/RIoTCrypt/include -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/c-utility/inc -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/serializer/inc -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/deps/parson -I../../../../../../../../Middlewares/Third_Party/mbedTLS/include -I../../../../../../../../Drivers/BSPv2/Components/es_wifi -I../../../../../../../../Drivers/BSPv2/Components/vl53l0x -I../../../../../BootLoader_OSC/Linker_Common -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Application/User/vl53l0x_platform.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/vl53l0x_proximity.o: /home/lu/Projects/STM32CubeExpansion_Cloud_AZURE_V1.2.1/Projects/B-L475E-IOT01A/Applications/Cloud/Azure/Src/vl53l0x_proximity.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32L475xx -DUSE_HAL_DRIVER -DSENSOR '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -DENABLE_IOT_INFO -DENABLE_IOT_ERROR -DENABLE_IOT_WARNING -DDONT_USE_UPLOADTOBLOB -DAZURE -DUSE_MBED_TLS -DHSM_TYPE_X509 -DHSM_TYPE_SAS_TOKEN -DUSE_PROV_MODULE '-DEINVAL=22' '-DENOMEM=12' '-DSTRINGS_C_SPRINTF_BUFFER_SIZE=512' -DUSE_WIFI -c -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSPv2/B-L475E-IOT01 -I../../../Inc -I../../../../../../../../Middlewares/ST/STM32_Connect_Library/Includes -I../../../../../../../../Middlewares/ST/STM32_Secure_Engine/Core -I../../../../../BootLoader_OSC/2_Images_SECoreBin/Inc -I../../../../../BootLoader_OSC/2_Images_SBSFU/SBSFU/App -I../../../../../BootLoader_OSC/Linker_Common/SW4STM32 -I../../../../../../../Misc_Utils/Inc -I../../../../../../../../Utilities/Time -I../../../../../../../../Utilities/CLD_utils/http_lib -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/umqtt/inc -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/iothub_client/inc -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/iothub_client/samples/STM32Cube_sample -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/provisioning_client/adapters -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/provisioning_client/inc -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/provisioning_client/deps/RIoT/Emulator/RIoT -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/provisioning_client/deps/RIoT/Emulator/DICE -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/provisioning_client/deps/RIoT/Emulator/RIoT/RIoTCrypt/include -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/c-utility/inc -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/serializer/inc -I../../../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/deps/parson -I../../../../../../../../Middlewares/Third_Party/mbedTLS/include -I../../../../../../../../Drivers/BSPv2/Components/es_wifi -I../../../../../../../../Drivers/BSPv2/Components/vl53l0x -I../../../../../BootLoader_OSC/Linker_Common -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Application/User/vl53l0x_proximity.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

